In [2]:
x=10
x+=12
y=int(x/4)
x=x+y

print(x,y)

27 5


In [5]:
a = 4

def polynome(a, b, c, x) : 
    return a*x**2 + b*x + c


b=a
b*=a
c=1

resultat = polynome(a, b, c, 0)

a+=3
a = 0 

print(resultat, a,b,c)

1 0 16 1


In [12]:
num = {'one':1,'two':3}
print(num)

num['two'] = 2
print(num)


{'one': 1, 'two': 3}
{'one': 1, 'two': 2}


In [13]:
numUser = input("?")

?Moimême


In [14]:
numUser 


'Moimême'

In [16]:
numUser.startswith("Moi ")

False

In [17]:
monString = "Eléments"

for elt in monString:
    print(elt)

E
l
é
m
e
n
t
s


In [27]:
d = {'a': 0, 'b': 1, 'c': 0}
print(d['d'])

if d['a'] > 0:
    print('yh !')
elif d['b'] > 0:
    print('yeah !')
elif d['c'] > 0:
    print('ok')
elif d['d'] > 0:
    print('ok')
else:
    print('not ok')

KeyError: 'd'

In [31]:
a = ['foo', 'bar', 'baz', 'qux', 'corge']



while a:
    if len(a) < 3:
        break
    print(a.pop())
print('Done.')

corge
qux
baz
Done.


In [35]:
import random

n = random.uniform(10,19)
print(n)

10.372658349614484


In [41]:
import random

panier = ["Pomme", "Poire", "Banane", "Ananas", "Orange"]
resultat = random.choice(panier)
print(resultat)

Banane


In [118]:
resultatJeu1 = []
issues = ["Pile","Face"]
for i in range (0,100000) : 
    resultatJeu1.append((random.choices(issues,weights=(0.49,0.51),k=1))[0])

"Pile" in resultatJeu1

nbPile = resultatJeu1.count("Pile")
nbFace = len(resultatJeu1) - nbPile

nbPile/len(resultatJeu1)


0.49232

In [189]:
init = 1000
capital1 = init




resultatJeu1 = []
issues = ["Pile","Face"]



for i in range(0,10000) :
    
    resultatJeu1.append((random.choices(issues,weights=(0.49,0.51)))[0])


    if resultatJeu1[-1]=="Pile" : 
        capital1 +=1 
    else : 
        capital1 -=1



resultatJeu2 = []
capital2 = init

for i in range(0,10000) : 

    if capital2%3 == 0 : 
        resultatJeu2.append((random.choices(issues,weights=(0.09,1-0.09)))[0])
    else :
        resultatJeu2.append((random.choices(issues,weights=(0.74,1-0.74)))[0])


    if resultatJeu2[-1]=="Pile" : 
        capital2 +=1 
    else : 
        capital2 -=1


    
print(capital1,capital2)
print(resultatJeu1)

880 852
['Pile', 'Face', 'Pile', 'Pile', 'Pile', 'Face', 'Face', 'Pile', 'Face', 'Face', 'Face', 'Pile', 'Face', 'Pile', 'Pile', 'Pile', 'Pile', 'Pile', 'Face', 'Pile', 'Face', 'Pile', 'Face', 'Face', 'Pile', 'Face', 'Pile', 'Pile', 'Pile', 'Face', 'Face', 'Face', 'Pile', 'Pile', 'Face', 'Face', 'Pile', 'Face', 'Face', 'Pile', 'Pile', 'Pile', 'Face', 'Face', 'Face', 'Face', 'Pile', 'Pile', 'Pile', 'Pile', 'Face', 'Pile', 'Face', 'Pile', 'Pile', 'Pile', 'Pile', 'Pile', 'Pile', 'Pile', 'Face', 'Pile', 'Pile', 'Face', 'Face', 'Pile', 'Face', 'Pile', 'Face', 'Face', 'Face', 'Pile', 'Face', 'Face', 'Face', 'Pile', 'Pile', 'Face', 'Face', 'Face', 'Face', 'Face', 'Face', 'Face', 'Pile', 'Face', 'Pile', 'Face', 'Pile', 'Face', 'Face', 'Pile', 'Face', 'Pile', 'Face', 'Pile', 'Face', 'Face', 'Pile', 'Pile', 'Pile', 'Pile', 'Face', 'Face', 'Pile', 'Pile', 'Pile', 'Face', 'Face', 'Face', 'Pile', 'Pile', 'Pile', 'Pile', 'Pile', 'Face', 'Face', 'Face', 'Face', 'Face', 'Face', 'Face', 'Pile', 'Face',

In [210]:
init = 1000
capital1 = init

resultatJeu1 = []
issues = ["Pile","Face"]


premierLance = random.choices(issues)

for i in range(0,100000) :

    if premierLance == "Pile" : 

            resultatJeu1.append((random.choices(issues,weights=(0.49,0.51)))[0])


            if resultatJeu1[-1]=="Pile" : 
                capital1 +=1 
            else : 
                capital1 -=1

    else : 
        if capital1%3 == 0 : 
            resultatJeu1.append((random.choices(issues,weights=(0.09,1-0.09)))[0])
        else :
            resultatJeu1.append((random.choices(issues,weights=(0.74,1-0.74)))[0])


        if resultatJeu1[-1]=="Pile" : 
            capital1 +=1 
        else : 
            capital1 -=1



print(capital1)
print(resultatJeu1)

-466
['Pile', 'Face', 'Pile', 'Pile', 'Face', 'Pile', 'Face', 'Pile', 'Face', 'Pile', 'Face', 'Pile', 'Face', 'Face', 'Pile', 'Pile', 'Face', 'Pile', 'Face', 'Pile', 'Face', 'Pile', 'Face', 'Face', 'Pile', 'Pile', 'Face', 'Face', 'Pile', 'Pile', 'Face', 'Face', 'Pile', 'Pile', 'Face', 'Pile', 'Face', 'Pile', 'Face', 'Pile', 'Face', 'Pile', 'Face', 'Pile', 'Face', 'Pile', 'Face', 'Face', 'Pile', 'Pile', 'Face', 'Face', 'Pile', 'Pile', 'Pile', 'Pile', 'Pile', 'Face', 'Pile', 'Face', 'Pile', 'Face', 'Face', 'Pile', 'Face', 'Pile', 'Pile', 'Face', 'Pile', 'Face', 'Pile', 'Face', 'Face', 'Pile', 'Pile', 'Face', 'Face', 'Pile', 'Face', 'Pile', 'Face', 'Pile', 'Pile', 'Face', 'Pile', 'Face', 'Pile', 'Pile', 'Pile', 'Face', 'Pile', 'Face', 'Face', 'Face', 'Pile', 'Face', 'Pile', 'Face', 'Pile', 'Face', 'Pile', 'Face', 'Pile', 'Face', 'Pile', 'Face', 'Pile', 'Face', 'Pile', 'Face', 'Pile', 'Face', 'Face', 'Pile', 'Face', 'Pile', 'Pile', 'Face', 'Pile', 'Face', 'Pile', 'Pile', 'Pile', 'Pile', 'F

In [212]:
population = range(1000) 

# Nombre de tickets souhaités 
N = 10

random.choices(population, k=N)


[884, 226, 137, 971, 843, 508, 541, 260, 546, 168]

In [209]:
capital1 = 2
capital1%3 == 0 

False

In [ ]:
# ARRAY et NUMPY

In [238]:
import numpy as np

myArray = np.arange(1,90)

print(myArray[::-1])
print(myArray[myArray>49])


a = np.linspace(5, 10, 11)

print(a)


a[a % 2 == 0]
print(a%2 ==0)
print(a[a % 2 == 0]
)


b = np.array([[[1, 2],[4, 5]],
        [[6, 7],[8, 9]],
        [[10, 11],[12, 13]]])


print(b)


np.vstack(b)

[89 88 87 86 85 84 83 82 81 80 79 78 77 76 75 74 73 72 71 70 69 68 67 66
 65 64 63 62 61 60 59 58 57 56 55 54 53 52 51 50 49 48 47 46 45 44 43 42
 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18
 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]
[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89]
[ 5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5 10. ]
[False False  True False False False  True False False False  True]
[ 6.  8. 10.]
[[[ 1  2]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]]]


array([[ 1,  2],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13]])

In [240]:
b = np.array([[[1, 2],[4, 5]],
        [[6, 7],[8, 9]],
        [[10, 11],[12, 13]]])

b[2, :, :]


array([[10, 11],
       [12, 13]])